language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - pip install behave
  - pip install pyhamcrest
# command to run tests
script: 
  - cd veryfay
  - behave