language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - pip install behave
  - pip install pyhamcrest
# command to run tests
script: 
  - cd veryfay
  - behave